name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ximaz'
      - run: bun install
      - run: bun publish --provenance --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
